const defaults = {
  osc1:   { enabled: true },
  filter: { rolloff: -24, enabled: true },
  lfo:    { enabled: true },
  effects: {
    chorus: { enabled: false },
    delay:  { enabled: false },
    reverb: { enabled: false, tone: 20000 },
  },
};

function p(preset) {
  return {
    ...preset,
    osc1:   { ...defaults.osc1,   ...preset.osc1 },
    filter: { ...defaults.filter, ...preset.filter },
    lfo:    { ...defaults.lfo,    ...preset.lfo },
    effects: {
      chorus: { ...defaults.effects.chorus, ...preset.effects.chorus },
      delay:  { ...defaults.effects.delay,  ...preset.effects.delay  },
      reverb: { ...defaults.effects.reverb, ...preset.effects.reverb },
    },
  };
}

export const PRESETS = [
  p({
    id: 'init', name: 'Init',
    osc1:   { type: 'sawtooth', octave: 0, detune: 0, volume: 0.8 },
    osc2:   { type: 'square',   octave: 0, semitone: 0, detune: 0, volume: 0, enabled: false },
    unison: { voices: 1, spread: 15, width: 0.5 },
    filter: { type: 'lowpass', frequency: 8000, Q: 1 },
    env:    { attack: 0.01, decay: 0.1, sustain: 0.8, release: 0.3 },
    lfo:    { type: 'sine', rate: 2, depth: 0, destination: 'filter' },
    effects: { chorus: { rate: 1.5, depth: 0.5, wet: 0 }, delay: { time: 0.25, feedback: 0.3, wet: 0 }, reverb: { decay: 2.5, wet: 0 } },
    amp: { volume: 0.75 },
  }),
  p({
    id: 'pad', name: 'Pad',
    osc1:   { type: 'sawtooth', octave: 0, detune: 5, volume: 0.7 },
    osc2:   { type: 'sawtooth', octave: 0, semitone: 0, detune: -5, volume: 0.6, enabled: true },
    unison: { voices: 4, spread: 20, width: 0.8 },
    filter: { type: 'lowpass', frequency: 1200, Q: 0.8 },
    env:    { attack: 0.8, decay: 0.3, sustain: 0.9, release: 1.5 },
    lfo:    { type: 'sine', rate: 0.3, depth: 0.15, destination: 'filter', enabled: true },
    effects: { chorus: { rate: 1.5, depth: 0.6, wet: 0.4, enabled: true }, delay: { time: 0.25, feedback: 0.3, wet: 0.1, enabled: true }, reverb: { decay: 4, wet: 0.6, enabled: true } },
    amp: { volume: 0.7 },
  }),
  p({
    id: 'lead', name: 'Lead',
    osc1:   { type: 'sawtooth', octave: 0, detune: 0, volume: 0.9 },
    osc2:   { type: 'square',   octave: 0, semitone: 12, detune: 0, volume: 0.3, enabled: true },
    unison: { voices: 2, spread: 10, width: 0.4 },
    filter: { type: 'lowpass', frequency: 3500, Q: 3 },
    env:    { attack: 0.01, decay: 0.15, sustain: 0.6, release: 0.2 },
    lfo:    { type: 'sine', rate: 5, depth: 0.05, destination: 'pitch', enabled: true },
    effects: { chorus: { rate: 2, depth: 0.3, wet: 0.15, enabled: true }, delay: { time: 0.25, feedback: 0.25, wet: 0.2, enabled: true }, reverb: { decay: 1.5, wet: 0.2, enabled: true } },
    amp: { volume: 0.75 },
  }),
  p({
    id: 'bass', name: 'Bass',
    osc1:   { type: 'sawtooth', octave: -1, detune: 0, volume: 0.9 },
    osc2:   { type: 'square',   octave: -1, semitone: 0, detune: 5, volume: 0.5, enabled: true },
    unison: { voices: 1, spread: 0, width: 0 },
    filter: { type: 'lowpass', frequency: 600, Q: 4, rolloff: -24 },
    env:    { attack: 0.005, decay: 0.2, sustain: 0.5, release: 0.15 },
    lfo:    { type: 'sine', rate: 2, depth: 0, destination: 'filter' },
    effects: { chorus: { rate: 1, depth: 0.2, wet: 0 }, delay: { time: 0.25, feedback: 0.2, wet: 0 }, reverb: { decay: 1, wet: 0.05, enabled: true } },
    amp: { volume: 0.8 },
  }),
  p({
    id: 'pluck', name: 'Pluck',
    osc1:   { type: 'sawtooth', octave: 0, detune: 0, volume: 0.8 },
    osc2:   { type: 'triangle', octave: 1, semitone: 0, detune: 3, volume: 0.4, enabled: true },
    unison: { voices: 2, spread: 8, width: 0.5 },
    filter: { type: 'lowpass', frequency: 4000, Q: 2 },
    env:    { attack: 0.001, decay: 0.3, sustain: 0.0, release: 0.5 },
    lfo:    { type: 'sine', rate: 2, depth: 0, destination: 'filter' },
    effects: { chorus: { rate: 2, depth: 0.3, wet: 0.1, enabled: true }, delay: { time: 0.25, feedback: 0.35, wet: 0.3, enabled: true }, reverb: { decay: 1.5, wet: 0.25, enabled: true } },
    amp: { volume: 0.75 },
  }),
  p({
    id: 'keys', name: 'Keys',
    osc1:   { type: 'triangle', octave: 0, detune: 0, volume: 0.85 },
    osc2:   { type: 'sine',     octave: 1, semitone: 0, detune: 0, volume: 0.5, enabled: true },
    unison: { voices: 1, spread: 0, width: 0 },
    filter: { type: 'lowpass', frequency: 6000, Q: 0.5 },
    env:    { attack: 0.005, decay: 0.4, sustain: 0.3, release: 0.8 },
    lfo:    { type: 'sine', rate: 2, depth: 0, destination: 'filter' },
    effects: { chorus: { rate: 1, depth: 0.3, wet: 0.2, enabled: true }, delay: { time: 0.25, feedback: 0.2, wet: 0.05, enabled: true }, reverb: { decay: 2, wet: 0.3, enabled: true } },
    amp: { volume: 0.75 },
  }),
  p({
    id: 'drift', name: 'Drift',
    osc1:   { type: 'sawtooth', octave: 0, detune: 8, volume: 0.7 },
    osc2:   { type: 'sawtooth', octave: -1, semitone: 0, detune: -8, volume: 0.6, enabled: true },
    unison: { voices: 7, spread: 25, width: 1.0 },
    filter: { type: 'lowpass', frequency: 900, Q: 1.5 },
    env:    { attack: 1.5, decay: 0.5, sustain: 0.8, release: 2.0 },
    lfo:    { type: 'sine', rate: 0.1, depth: 0.3, destination: 'filter', enabled: true },
    effects: { chorus: { rate: 0.5, depth: 0.8, wet: 0.5, enabled: true }, delay: { time: 0.5, feedback: 0.5, wet: 0.2, enabled: true }, reverb: { decay: 6, wet: 0.7, enabled: true } },
    amp: { volume: 0.65 },
  }),
];
